### ISSUE TITLE
Demo to support iOS 5

### ISSUE THREAD

**Issue by saturngod** [adamdebono/ADSlidingViewController#2]
Testing demo and it's not working with iOS 5 because of `setRestorationIdentifier` only work at iOS 6.0 or later.

in ADSlidingViewController.m , line 108 should be like

```
if([self respondsToSelector:@selector(setRestorationIdentifier:)]) {
        [self setRestorationIdentifier:kADStateRestorationIdentifier];
        [self setRestorationClass:[self class]];
}
```

**Comment by adamdebono** [comment]
Fixed!

adamdebono/ADSlidingViewController@8cdeee21fd124580c6b61fe94ed6d5123e5cea37
